-- Create test alerts to simulate what the alert-monitor should have created
INSERT INTO public.alerts (
  title, 
  description, 
  priority, 
  sensor_type, 
  sensor_location, 
  sensor_value, 
  threshold_value, 
  status,
  severity,
  category,
  equipment,
  location,
  sensor,
  value,
  threshold,
  unit,
  created_at
) VALUES 
(
  'P2 Temperature Alert', 
  'Temperature reading of 35°C exceeds threshold of 25°C at Hangar A', 
  'P2', 
  'temperature', 
  'Hangar A', 
  35, 
  25, 
  'active',
  'high',
  'environmental',
  'Temperature Sensor',
  'Hangar A',
  'Temp-001',
  '35',
  '25',
  '°C',
  NOW()
),
(
  'P2 Humidity Alert', 
  'Humidity reading of 70% exceeds threshold of 60% at Hangar A', 
  'P2', 
  'humidity', 
  'Hangar A', 
  70, 
  60, 
  'active',
  'high',
  'environmental',
  'Humidity Sensor',
  'Hangar A',
  'Hum-001',
  '70',
  '60',
  '%',
  NOW()
),
(
  'P2 Vibration Alert', 
  'Dangerous vibration level detected: 12 units at Hangar A. Urgent inspection required.', 
  'P2', 
  'vibration', 
  'Hangar A', 
  12, 
  10, 
  'active',
  'high',
  'equipment',
  'Vibration Sensor',
  'Hangar A',
  'Vib-001',
  '12',
  '10',
  'units',
  NOW()
);