// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txnghrvynzrxvshoctpk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4bmdocnZ5bnpyeHZzaG9jdHBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MzkzNDMsImV4cCI6MjA2OTExNTM0M30.ZrA0TqpNKLy85_7raObo3lzXvBr-lK2crDgPJiUZCdw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});